# Generated by Django 3.0.7 on 2021-03-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj5FinTracker', '0002_auto_20210222_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_doc', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
